// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// IMPORTANT: Run this command from the project root to replace this file
/// with your real platform credentials:
///
///   dart pub global activate flutterfire_cli
///   flutterfire configure --project=edupal-app-8ccb1
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXujFW_TjAtkgOuxEMdhAHy_UWpVlW6YI',
    appId: '1:494545154949:web:49d292cbe8a40848208aec',
    messagingSenderId: '494545154949',
    projectId: 'edupal-app-8ccb1',
    authDomain: 'edupal-app-8ccb1.firebaseapp.com',
    storageBucket: 'edupal-app-8ccb1.firebasestorage.app',
    measurementId: 'G-GB1YR0GH3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADOxCX75BarcFFxuOTtsJhkesFgqZk84c',
    appId: '1:494545154949:android:9ff9d63d1f81c174208aec',
    messagingSenderId: '494545154949',
    projectId: 'edupal-app-8ccb1',
    storageBucket: 'edupal-app-8ccb1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6HjfixgqVImwcVfW9lPmf2yvbRCTC164',
    appId: '1:494545154949:ios:17e75c6f92fd1046208aec',
    messagingSenderId: '494545154949',
    projectId: 'edupal-app-8ccb1',
    storageBucket: 'edupal-app-8ccb1.firebasestorage.app',
    iosClientId: '494545154949-qd04cgq5tmua853taueoicbibpi3duln.apps.googleusercontent.com',
    iosBundleId: 'com.example.libview',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6HjfixgqVImwcVfW9lPmf2yvbRCTC164',
    appId: '1:494545154949:ios:17e75c6f92fd1046208aec',
    messagingSenderId: '494545154949',
    projectId: 'edupal-app-8ccb1',
    storageBucket: 'edupal-app-8ccb1.firebasestorage.app',
    iosClientId: '494545154949-qd04cgq5tmua853taueoicbibpi3duln.apps.googleusercontent.com',
    iosBundleId: 'com.example.libview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXujFW_TjAtkgOuxEMdhAHy_UWpVlW6YI',
    appId: '1:494545154949:web:0a93e6450494a9ca208aec',
    messagingSenderId: '494545154949',
    projectId: 'edupal-app-8ccb1',
    authDomain: 'edupal-app-8ccb1.firebaseapp.com',
    storageBucket: 'edupal-app-8ccb1.firebasestorage.app',
    measurementId: 'G-Z67KMHE8LP',
  );
}
